export const API = 'https://hi-doctor-emirbek-aktilek.herokuapp.com/api'
export const APIusers = 'https://hi-doctor-emirbek-aktilek.herokuapp.com/api/users'
export const APIservices = 'https://hi-doctor-emirbek-aktilek.herokuapp.com/api/service'
export const APIcomments = 'https://hi-doctor-emirbek-aktilek.herokuapp.com/api/service'
export const APIfeedbacks = 'https://hi-doctor-emirbek-aktilek.herokuapp.com/api/feedbacks'
