export const API = 'https://hi-doctor-emirbek-aktilek.herokuapp.com/api'
export const APIusers = 'https://hi-doctor-emirbek-aktilek.herokuapp.com/users/api'
export const APIservices = 'https://hi-doctor-emirbek-aktilek.herokuapp.com/service/api'
export const APIcomments = 'https://hi-doctor-emirbek-aktilek.herokuapp.com/comments/api'
export const APIfeedbacks = 'https://hi-doctor-emirbek-aktilek.herokuapp.com/feedbacks/api'
